### ISSUE TITLE
Stuck on "booting" message for all games except first

### ISSUE THREAD

**Issue by aaronjmill** [retrohead/satiator-rings#13]
Japanese saturn, Phantom IC installed, no AR. Rings used to work fine with this setup but since adding cover art and updating to latest I've been unable to boot anything but the game at the top of the list. The game is written to the autoboot file successfully. Gets through every step of loading without error until it just hangs at "Booting..."

**Comment by retrohead** [comment]
Please check your installation files. It sounds like you are using the option  Auto Region Patch: Emu.  There are other options you can try too.

This loads a modified copy of the menu from the satiator rings directory so make sure you have updated the whole satiator-rings folder and not just the autoboot.iso.

If in doubt, delete the entire satiator-rings folder and start again. Make sure to make a backup first.
