### ISSUE TITLE
Issue with FW160 and rings menu

### ISSUE THREAD

**Issue by klandrith** [retrohead/satiator-rings#17]
Upgraded to satiator FW160 and now satiator rings won't load. Don't know if this is a satiator or rings issue.

**Comment by privateye** [comment]
Satiator Rings v5.5 loads fine for me on FW160, and games will boot as long as `Auto Region Patch` is set to `On` (not `Off` or `Emu`). This setting is accessible by pressing Start in the games menu and then selecting `Options`.

**Comment by klandrith** [comment]
Thank you for the confirmation. I will try it again.

**Comment by retrohead** [comment]
Duplicate
