### ISSUE TITLE
For unidentified game, config tool shows ID of last identified game

### ISSUE THREAD

**Issue by arromdee** [retrohead/satiator-rings#8]
If you go into your game list and click on a game,the panel on the right has an image, an ID, and a version number.  But if the game has nothing, it keeps the ID and version of the last game you clicked on that had a valid ID.

It should instead clear those fields to be blank.

**Comment by retrohead** [comment]
Thanks, this is committed in v4.7a of the config tool but no binary is available yet.

https://github.com/retrohead/satiator-rings-config
